spring:
  application:
    name: blog-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
server:
  port: 8803

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400